version: '3.3'

services:
  api:
    image: timoa/app-stores-prometheus-exporter:latest@sha256:725ead64d8492131a4998f36cd633eb5bbb363df623d2dd5ae5b2b763545e12f
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/opt/app/config
    ports:
      - 9514:9514
    restart: always

volumes:
  config:
