version: '3.3'

services:
  api:
    image: timoa/app-stores-prometheus-exporter:latest@sha256:385d7513c04ebb147de1ff1ea5676d79fd62efb46f0c2c358150ccdf10a076c4
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9514:9514
    restart: always
